version: '3'
services:
  java-srv:
    build:
      context: java-srv
    volumes:
      - ./java-srv/log:/root/log
    depends_on:
      - db
    links:
      - "db:db"

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass
